export const MOCK_USER = {
  id: 'usr-01',
  name: 'Dinesh Kumar',
  email: 'dinesh@drivenearby.ai',
  phone: '+91 98765 43210',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&q=80',
  memberSince: 'March 2024',
  totalBookings: 14,
  ratingsGiven: 12,
  savedLocations: [
    { id: 'loc-1', label: 'Home', address: 'Indiranagar 100ft Road, Bengaluru', icon: 'home' },
    { id: 'loc-2', label: 'Work', address: 'RMZ Ecoworld, Bellandur, Bengaluru', icon: 'briefcase' },
    { id: 'loc-3', label: 'Gym', address: 'Cult.Fit, Koramangala 4th Block', icon: 'fitness' },
  ],
};

export const INITIAL_DRIVERS = [
  {
    id: 'drv-01',
    name: 'Ravi Kumar',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    phone: '+91 98450 12345',
    experienceYears: 7,
    licenseNumber: 'KA-01-2018-009182',
    verified: true,
    rating: 4.8,
    totalRatings: 128,
    completedTrips: 142,
    cancellationRate: 1.1,
    trustScore: 94,
    badge: 'Elite Verified Pro',
    pricing: {
      perHour: 150,
      perDay: 800,
    },
    availability: 'available',
    distanceKm: 1.6,
    address: 'Indiranagar 100ft Road, Bengaluru',
    coordinates: { latitude: 12.9784, longitude: 77.6408 },
    languages: ['English', 'Hindi', 'Kannada'],
    vehicleSkills: ['Sedan', 'SUV', 'Automatic', 'Manual', 'Night Highway'],
    trustBreakdown: {
      identityVerified: 99,
      safetyRecord: 96,
      punctuality: 95,
      customerSatisfaction: 94,
    },
    aiMatchScore: 94,
    aiRecommendationReason: 'Ultra-nearby (1.6 km away), 4.8★ top feedback, 142+ verified trips, zero incident record.',
    aiBadge: 'Top AI Match',
    recentReviews: [
      {
        id: 'rev-01',
        userName: 'Aakash Verma',
        rating: 5,
        date: '2 days ago',
        comment: 'Very polite, smooth driving in peak Bangalore traffic. Extremely punctual.',
      },
      {
        id: 'rev-02',
        userName: 'Priya Sundaram',
        rating: 4.8,
        date: '1 week ago',
        comment: 'Handled airport drop at 4 AM effortlessly. Highly recommended driver!',
      },
    ],
  },
  {
    id: 'drv-02',
    name: 'Suresh Reddy',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    phone: '+91 97412 87654',
    experienceYears: 9,
    licenseNumber: 'KA-05-2015-004412',
    verified: true,
    rating: 4.9,
    totalRatings: 185,
    completedTrips: 210,
    cancellationRate: 0.8,
    trustScore: 97,
    badge: 'Top Rated Star',
    pricing: {
      perHour: 170,
      perDay: 950,
    },
    availability: 'available',
    distanceKm: 2.3,
    address: 'Koramangala 5th Block, Bengaluru',
    coordinates: { latitude: 12.9352, longitude: 77.6229 },
    languages: ['Telugu', 'Kannada', 'English', 'Hindi'],
    vehicleSkills: ['Luxury Sedans', 'SUV', 'Electric Vehicles', 'Hilly Terrain'],
    trustBreakdown: {
      identityVerified: 100,
      safetyRecord: 98,
      punctuality: 97,
      customerSatisfaction: 96,
    },
    aiMatchScore: 91,
    aiRecommendationReason: 'Highest customer retention (98% repeat preference) & pristine safety record.',
    aiBadge: 'VIP Choice',
    recentReviews: [
      {
        id: 'rev-03',
        userName: 'Vikram Joshi',
        rating: 5,
        date: 'Yesterday',
        comment: 'Suresh is an absolute gentleman. Drove our family safely to Mysore and back.',
      },
    ],
  },
  {
    id: 'drv-03',
    name: 'Arun Kumar',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    phone: '+91 99001 54321',
    experienceYears: 4,
    licenseNumber: 'KA-03-2020-008219',
    verified: true,
    rating: 4.7,
    totalRatings: 76,
    completedTrips: 88,
    cancellationRate: 2.1,
    trustScore: 89,
    badge: 'Reliable Partner',
    pricing: {
      perHour: 140,
      perDay: 750,
    },
    availability: 'available',
    distanceKm: 3.1,
    address: 'HSR Layout Sector 2, Bengaluru',
    coordinates: { latitude: 12.9116, longitude: 77.6433 },
    languages: ['Tamil', 'Kannada', 'English'],
    vehicleSkills: ['Hatchback', 'Sedan', 'Manual'],
    trustBreakdown: {
      identityVerified: 96,
      safetyRecord: 90,
      punctuality: 92,
      customerSatisfaction: 88,
    },
    aiMatchScore: 84,
    aiRecommendationReason: 'Best budget value in your sector with strong local Bengaluru navigation.',
    aiBadge: 'Budget Pick',
    recentReviews: [
      {
        id: 'rev-04',
        userName: 'Sneha Patel',
        rating: 4.6,
        date: '4 days ago',
        comment: 'Great driving skills and knows all shortcut routes around Silk Board.',
      },
    ],
  },
  {
    id: 'drv-04',
    name: 'Kiran Rao',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
    phone: '+91 98860 99887',
    experienceYears: 6,
    licenseNumber: 'KA-51-2018-001239',
    verified: true,
    rating: 4.8,
    totalRatings: 110,
    completedTrips: 124,
    cancellationRate: 1.4,
    trustScore: 92,
    badge: 'Verified Specialist',
    pricing: {
      perHour: 160,
      perDay: 850,
    },
    availability: 'available',
    distanceKm: 4.2,
    address: 'Whitefield Main Road, Bengaluru',
    coordinates: { latitude: 12.9698, longitude: 77.7499 },
    languages: ['English', 'Hindi', 'Kannada', 'Marathi'],
    vehicleSkills: ['SUV', 'Automatic', 'Night Driving', 'VIP Escort'],
    trustBreakdown: {
      identityVerified: 98,
      safetyRecord: 94,
      punctuality: 93,
      customerSatisfaction: 92,
    },
    aiMatchScore: 82,
    aiRecommendationReason: 'Specialized in automatic SUVs and long-distance city commute.',
    aiBadge: 'SUV Specialist',
    recentReviews: [
      {
        id: 'rev-05',
        userName: 'Rohan Mehra',
        rating: 5,
        date: '3 days ago',
        comment: 'Drove my Audi Q5 very carefully. Clean uniform and very courteous.',
      },
    ],
  },
];

export const INITIAL_CARS = [
  {
    id: 'car-01',
    name: 'Hyundai Creta',
    brand: 'Hyundai',
    category: 'SUV',
    carImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=600&q=80',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    seats: 5,
    rating: 4.8,
    completedTrips: 112,
    verified: true,
    pricePerDay: 1800,
    pricePerHour: 220,
    deposit: 3000,
    availability: 'available',
    distanceKm: 2.1,
    address: 'Koramangala 4th Block, Bengaluru',
    coordinates: { latitude: 12.934, longitude: 77.625 },
    features: ['Panoramic Sunroof', 'Airbags', 'GPS Navigation', 'Fastag', 'Cruise Control', 'Bluetooth Sound'],
    owner: {
      name: 'CityWheelz Bangalore',
      verified: true,
      rating: 4.9,
    },
    trustScore: 94,
    aiMatchScore: 93,
    aiBadge: 'Most Popular SUV',
    aiRecommendationReason: 'Close to your location (2.1 km), spotless maintenance record & automated sanitization check.',
  },
  {
    id: 'car-02',
    name: 'Tata Nexon',
    brand: 'Tata',
    category: 'Compact SUV',
    carImage: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=600&q=80',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 5,
    rating: 4.7,
    completedTrips: 84,
    verified: true,
    pricePerDay: 1500,
    pricePerHour: 190,
    deposit: 2500,
    availability: 'available',
    distanceKm: 1.4,
    address: 'Indiranagar 12th Main, Bengaluru',
    coordinates: { latitude: 12.975, longitude: 77.639 },
    features: ['5-Star GNCAP Safety', 'Reverse Camera', 'Fastag', 'Touchscreen Infotainment'],
    owner: {
      name: 'DriveNearby Fleet',
      verified: true,
      rating: 4.8,
    },
    trustScore: 92,
    aiMatchScore: 89,
    aiBadge: 'Safety First',
    aiRecommendationReason: '5-star crash safety certification and only 1.4 km from your detected pin.',
  },
  {
    id: 'car-03',
    name: 'Maruti Suzuki Brezza',
    brand: 'Maruti Suzuki',
    category: 'Compact SUV',
    carImage: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=600&q=80',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    rating: 4.6,
    completedTrips: 130,
    verified: true,
    pricePerDay: 1400,
    pricePerHour: 180,
    deposit: 2000,
    availability: 'available',
    distanceKm: 3.5,
    address: 'HSR Layout Sector 1, Bengaluru',
    coordinates: { latitude: 12.914, longitude: 77.638 },
    features: ['SmartPlay Pro', 'Dual Airbags', 'Fastag', 'High Fuel Mileage'],
    owner: {
      name: 'Veloce Rentals',
      verified: true,
      rating: 4.7,
    },
    trustScore: 90,
    aiMatchScore: 83,
    aiBadge: 'Best Economy',
    aiRecommendationReason: 'Low security deposit and economical daily rate for city hopping.',
  },
  {
    id: 'car-04',
    name: 'Kia Seltos',
    brand: 'Kia',
    category: 'SUV',
    carImage: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=600&q=80',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    seats: 5,
    rating: 4.9,
    completedTrips: 160,
    verified: true,
    pricePerDay: 2100,
    pricePerHour: 260,
    deposit: 3500,
    availability: 'available',
    distanceKm: 2.8,
    address: 'Domlur Layout, Bengaluru',
    coordinates: { latitude: 12.961, longitude: 77.635 },
    features: ['Bose Premium Audio', 'Ventilated Seats', 'ADAS Level 2', 'Sunroof', 'Air Purifier'],
    owner: {
      name: 'PrimeDrive Luxe',
      verified: true,
      rating: 4.9,
    },
    trustScore: 96,
    aiMatchScore: 95,
    aiBadge: 'Premium Luxury',
    aiRecommendationReason: 'Fully loaded top-end variant with ADAS safety and premium sound system.',
  },
];

export const INITIAL_COMBOS = [
  {
    id: 'combo-01',
    driver: INITIAL_DRIVERS[0], // Ravi Kumar
    car: INITIAL_CARS[0],       // Hyundai Creta
    comboPricePerDay: 2400,
    savingsAmount: 200,
    distanceKm: 2.1,
    aiRecommendationReason: 'Best-matched combo: Ravi has 40+ prior trips specifically in this Hyundai Creta.',
    matchScore: 96,
    badge: 'AI Top Recommendation',
  },
  {
    id: 'combo-02',
    driver: INITIAL_DRIVERS[1], // Suresh Reddy
    car: INITIAL_CARS[3],       // Kia Seltos
    comboPricePerDay: 2800,
    savingsAmount: 250,
    distanceKm: 2.5,
    aiRecommendationReason: 'Executive combo with luxury vehicle and 97 Trust Score veteran driver.',
    matchScore: 97,
    badge: 'Executive Choice',
  },
  {
    id: 'combo-03',
    driver: INITIAL_DRIVERS[2], // Arun Kumar
    car: INITIAL_CARS[1],       // Tata Nexon
    comboPricePerDay: 2050,
    savingsAmount: 200,
    distanceKm: 1.8,
    aiRecommendationReason: 'Best value 5-star safety package for family city & highway travels.',
    matchScore: 91,
    badge: 'Safe & Economical',
  },
];

export const INITIAL_BOOKINGS = [
  {
    id: 'DN-829140',
    bookingId: 'DN-829140',
    serviceType: 'driver',
    driver: INITIAL_DRIVERS[0],
    pickupLocation: { address: 'Indiranagar 100ft Rd, Bengaluru', latitude: 12.9784, longitude: 77.6408 },
    destination: { address: 'Kempegowda Int. Airport (BLR)', latitude: 13.1986, longitude: 77.7066 },
    bookingDate: 'Today',
    startTime: '10:00 AM',
    duration: 'Airport Transfer (4 hrs)',
    estimatedPrice: 850,
    status: 'driver_arrived', // actively in progress
    reviewSubmitted: false,
    createdAt: new Date().toISOString(),
    tripMetrics: {
      distanceKm: 34.2,
      durationMinutes: 48,
    },
  },
  {
    id: 'DN-774129',
    bookingId: 'DN-774129',
    serviceType: 'combo',
    driver: INITIAL_DRIVERS[1],
    car: INITIAL_CARS[3],
    pickupLocation: { address: 'HSR Layout Sector 4, Bengaluru', latitude: 12.9116, longitude: 77.6433 },
    destination: { address: 'Nandi Hills Outstation Day Trip', latitude: 13.3702, longitude: 77.6835 },
    bookingDate: 'Yesterday',
    startTime: '06:00 AM',
    duration: 'Full Day (10 hrs)',
    estimatedPrice: 2800,
    status: 'trip_completed',
    reviewSubmitted: true,
    userRating: 5.0,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    tripMetrics: {
      distanceKm: 126.0,
      durationMinutes: 480,
    },
  },
  {
    id: 'DN-612048',
    bookingId: 'DN-612048',
    serviceType: 'car',
    car: INITIAL_CARS[1],
    pickupLocation: { address: 'Koramangala 5th Block, Bengaluru', latitude: 12.9352, longitude: 77.6229 },
    destination: { address: 'Mysore Road Self-Drive', latitude: 12.2958, longitude: 76.6394 },
    bookingDate: '24 Sep 2026',
    startTime: '08:00 AM',
    duration: '2 Days Rental',
    estimatedPrice: 3000,
    status: 'trip_completed',
    reviewSubmitted: true,
    userRating: 4.8,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    tripMetrics: {
      distanceKm: 280.0,
      durationMinutes: 1200,
    },
  },
];
