/**
 * Seed & Demo Data for DriveNearby AI
 * Realistic Indian mobility data with verified drivers, cars, and combo packages.
 */

const mockDrivers = [
  {
    id: 'drv-01',
    _id: '6601a1b2c3d4e5f6a7b8c901',
    name: 'Ravi Kumar',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    phone: '+91 98450 12345',
    experienceYears: 7,
    licenseNumber: 'KA-01-2018-009182',
    verified: true,
    rating: 4.8,
    totalRatings: 128,
    completedTrips: 142,
    cancellationRate: 1.1,
    trustScore: 94,
    badge: 'Elite Verified Pro',
    pricing: {
      perHour: 150,
      perDay: 800,
    },
    availability: 'available',
    distanceKm: 1.6,
    address: 'Indiranagar 100ft Road, Bengaluru',
    location: {
      type: 'Point',
      coordinates: [77.6408, 12.9784],
    },
    languages: ['English', 'Hindi', 'Kannada'],
    vehicleSkills: ['Sedan', 'SUV', 'Automatic', 'Manual', 'Highway Long Drive'],
    trustBreakdown: {
      identityVerified: 99,
      safetyRecord: 96,
      punctuality: 95,
      customerSatisfaction: 94,
    },
    recentReviews: [
      {
        id: 'rev-01',
        userName: 'Aakash Verma',
        rating: 5,
        date: '2 days ago',
        comment: 'Very polite, smooth driving in heavy Bangalore traffic. Extremely punctual.',
      },
      {
        id: 'rev-02',
        userName: 'Priya Sundaram',
        rating: 4.8,
        date: '1 week ago',
        comment: 'Handled airport drop at 4 AM effortlessly. Highly recommended driver!',
      },
    ],
  },
  {
    id: 'drv-02',
    _id: '6601a1b2c3d4e5f6a7b8c902',
    name: 'Suresh Reddy',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    phone: '+91 97412 87654',
    experienceYears: 9,
    licenseNumber: 'KA-05-2015-004412',
    verified: true,
    rating: 4.9,
    totalRatings: 185,
    completedTrips: 210,
    cancellationRate: 0.8,
    trustScore: 97,
    badge: 'Top Rated Star',
    pricing: {
      perHour: 170,
      perDay: 950,
    },
    availability: 'available',
    distanceKm: 2.3,
    address: 'Koramangala 5th Block, Bengaluru',
    location: {
      type: 'Point',
      coordinates: [77.6229, 12.9352],
    },
    languages: ['Telugu', 'Kannada', 'English', 'Hindi'],
    vehicleSkills: ['Luxury Sedans', 'SUV', 'Electric Vehicles', 'Hilly Terrain'],
    trustBreakdown: {
      identityVerified: 100,
      safetyRecord: 98,
      punctuality: 97,
      customerSatisfaction: 96,
    },
    recentReviews: [
      {
        id: 'rev-03',
        userName: 'Vikram Joshi',
        rating: 5,
        date: 'Yesterday',
        comment: 'Suresh is an absolute gentleman. Drove our family safely to Mysore and back.',
      },
    ],
  },
  {
    id: 'drv-03',
    _id: '6601a1b2c3d4e5f6a7b8c903',
    name: 'Arun Kumar',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    phone: '+91 99001 54321',
    experienceYears: 4,
    licenseNumber: 'KA-03-2020-008219',
    verified: true,
    rating: 4.7,
    totalRatings: 76,
    completedTrips: 88,
    cancellationRate: 2.1,
    trustScore: 89,
    badge: 'Reliable Partner',
    pricing: {
      perHour: 140,
      perDay: 750,
    },
    availability: 'available',
    distanceKm: 3.1,
    address: 'HSR Layout Sector 2, Bengaluru',
    location: {
      type: 'Point',
      coordinates: [77.6433, 12.9116],
    },
    languages: ['Tamil', 'Kannada', 'English'],
    vehicleSkills: ['Hatchback', 'Sedan', 'Manual'],
    trustBreakdown: {
      identityVerified: 96,
      safetyRecord: 90,
      punctuality: 92,
      customerSatisfaction: 88,
    },
    recentReviews: [
      {
        id: 'rev-04',
        userName: 'Sneha Patel',
        rating: 4.6,
        date: '4 days ago',
        comment: 'Great driving skills and knows all shortcut routes around Silk Board.',
      },
    ],
  },
  {
    id: 'drv-04',
    _id: '6601a1b2c3d4e5f6a7b8c904',
    name: 'Kiran Rao',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
    phone: '+91 98860 99887',
    experienceYears: 6,
    licenseNumber: 'KA-51-2018-001239',
    verified: true,
    rating: 4.8,
    totalRatings: 110,
    completedTrips: 124,
    cancellationRate: 1.4,
    trustScore: 92,
    badge: 'Verified Specialist',
    pricing: {
      perHour: 160,
      perDay: 850,
    },
    availability: 'available',
    distanceKm: 4.2,
    address: 'Whitefield Main Road, Bengaluru',
    location: {
      type: 'Point',
      coordinates: [77.7499, 12.9698],
    },
    languages: ['English', 'Hindi', 'Kannada', 'Marathi'],
    vehicleSkills: ['SUV', 'Automatic', 'Night Driving', 'VIP Escort'],
    trustBreakdown: {
      identityVerified: 98,
      safetyRecord: 94,
      punctuality: 93,
      customerSatisfaction: 92,
    },
    recentReviews: [
      {
        id: 'rev-05',
        userName: 'Rohan Mehra',
        rating: 5,
        date: '3 days ago',
        comment: 'Drove my Audi Q5 very carefully. Clean uniform and very courteous.',
      },
    ],
  },
];

const mockCars = [
  {
    id: 'car-01',
    _id: '6601a2b2c3d4e5f6a7b8c911',
    name: 'Hyundai Creta',
    brand: 'Hyundai',
    category: 'SUV',
    carImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=600&q=80',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    seats: 5,
    rating: 4.8,
    completedTrips: 112,
    verified: true,
    pricePerDay: 1800,
    pricePerHour: 220,
    deposit: 3000,
    availability: 'available',
    distanceKm: 2.1,
    address: 'Koramangala 4th Block, Bengaluru',
    location: {
      type: 'Point',
      coordinates: [77.625, 12.934],
    },
    features: ['Panoramic Sunroof', 'Airbags', 'GPS Navigation', 'Fastag', 'Cruise Control', 'Bluetooth Sound'],
    owner: {
      name: 'CityWheelz Bangalore',
      verified: true,
      rating: 4.9,
    },
    trustScore: 94,
  },
  {
    id: 'car-02',
    _id: '6601a2b2c3d4e5f6a7b8c912',
    name: 'Tata Nexon',
    brand: 'Tata',
    category: 'Compact SUV',
    carImage: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=600&q=80',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 5,
    rating: 4.7,
    completedTrips: 84,
    verified: true,
    pricePerDay: 1500,
    pricePerHour: 190,
    deposit: 2500,
    availability: 'available',
    distanceKm: 1.4,
    address: 'Indiranagar 12th Main, Bengaluru',
    location: {
      type: 'Point',
      coordinates: [77.639, 12.975],
    },
    features: ['5-Star GNCAP Safety', 'Reverse Camera', 'Fastag', 'Touchscreen Infotainment'],
    owner: {
      name: 'DriveNearby Fleet',
      verified: true,
      rating: 4.8,
    },
    trustScore: 92,
  },
  {
    id: 'car-03',
    _id: '6601a2b2c3d4e5f6a7b8c913',
    name: 'Maruti Suzuki Brezza',
    brand: 'Maruti Suzuki',
    category: 'Compact SUV',
    carImage: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=600&q=80',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    rating: 4.6,
    completedTrips: 130,
    verified: true,
    pricePerDay: 1400,
    pricePerHour: 180,
    deposit: 2000,
    availability: 'available',
    distanceKm: 3.5,
    address: 'HSR Layout Sector 1, Bengaluru',
    location: {
      type: 'Point',
      coordinates: [77.638, 12.914],
    },
    features: ['SmartPlay Pro', 'Dual Airbags', 'Fastag', 'High Mileage'],
    owner: {
      name: 'Veloce Rentals',
      verified: true,
      rating: 4.7,
    },
    trustScore: 90,
  },
  {
    id: 'car-04',
    _id: '6601a2b2c3d4e5f6a7b8c914',
    name: 'Kia Seltos',
    brand: 'Kia',
    category: 'SUV',
    carImage: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=600&q=80',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    seats: 5,
    rating: 4.9,
    completedTrips: 160,
    verified: true,
    pricePerDay: 2100,
    pricePerHour: 260,
    deposit: 3500,
    availability: 'available',
    distanceKm: 2.8,
    address: 'Domlur Layout, Bengaluru',
    location: {
      type: 'Point',
      coordinates: [77.635, 12.961],
    },
    features: ['Bose Premium Audio', 'Ventilated Seats', 'ADAS Level 2', 'Sunroof', 'Air Purifier'],
    owner: {
      name: 'PrimeDrive Luxe',
      verified: true,
      rating: 4.9,
    },
    trustScore: 96,
  },
];

const mockCombos = [
  {
    id: 'combo-01',
    driver: mockDrivers[0], // Ravi Kumar
    car: mockCars[0],       // Hyundai Creta
    comboPricePerDay: 2400,
    discountAmount: 200,
    distanceKm: 2.1,
    aiRecommendationReason: 'Best-rated driver matched with luxury SUV located within 2 km.',
    matchScore: 95,
  },
  {
    id: 'combo-02',
    driver: mockDrivers[1], // Suresh Reddy
    car: mockCars[3],       // Kia Seltos
    comboPricePerDay: 2800,
    discountAmount: 250,
    distanceKm: 2.5,
    aiRecommendationReason: 'VIP combination for outstation and premium business journeys.',
    matchScore: 97,
  },
  {
    id: 'combo-03',
    driver: mockDrivers[2], // Arun Kumar
    car: mockCars[1],       // Tata Nexon
    comboPricePerDay: 2050,
    discountAmount: 200,
    distanceKm: 1.8,
    aiRecommendationReason: 'Safe 5-Star rated vehicle with certified local Bengaluru navigator.',
    matchScore: 91,
  },
];

const mockBookings = [
  {
    id: 'DN-829140',
    bookingId: 'DN-829140',
    serviceType: 'driver',
    driver: mockDrivers[0],
    pickupLocation: { address: 'Indiranagar 12th Main, Bengaluru' },
    destination: { address: 'Kempegowda Int. Airport (BLR)' },
    bookingDate: 'Today',
    startTime: '10:00 AM',
    duration: 'Airport Transfer (4 hrs)',
    estimatedPrice: 850,
    status: 'in_progress', // Active trip candidate
    reviewSubmitted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'DN-774129',
    bookingId: 'DN-774129',
    serviceType: 'combo',
    driver: mockDrivers[1],
    car: mockCars[3],
    pickupLocation: { address: 'HSR Layout Sector 4, Bengaluru' },
    destination: { address: 'Nandi Hills Outstation Day Trip' },
    bookingDate: 'Yesterday',
    startTime: '06:00 AM',
    duration: 'Full Day (10 hrs)',
    estimatedPrice: 2800,
    status: 'trip_completed',
    reviewSubmitted: true,
    userRating: 5.0,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'DN-612048',
    bookingId: 'DN-612048',
    serviceType: 'car',
    car: mockCars[1],
    pickupLocation: { address: 'Koramangala 5th Block, Bengaluru' },
    destination: { address: 'Mysore Road Self-Drive' },
    bookingDate: '24 Sep 2026',
    startTime: '08:00 AM',
    duration: '2 Days Rental',
    estimatedPrice: 3000,
    status: 'trip_completed',
    reviewSubmitted: true,
    userRating: 4.8,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
];

module.exports = {
  mockDrivers,
  mockCars,
  mockCombos,
  mockBookings,
};
